apiVersion: batch/v1
kind: Job
metadata:
  name: watch
spec:
  template:
    spec:
      securityContext:
        fsGroup: 65533
      serviceAccount: root-reconciler
      serviceAccountName: root-reconciler
      restartPolicy: Never
      containers:
      - name: watch
        image: gcr.io/haiyanmeng-anthos/watch:latest
        imagePullPolicy: Always
        args: ["--count", "1000", "--qps", "10"]
        resources:
          limits:
            cpu: "1"
            memory: 900Mi
          requests:
            cpu: "10m"
            memory: 10Mi
